"""added_admin_status_default

Revision ID: 774374f1ee34
Revises: ba5640e9887e
Create Date: 2024-01-30 16:20:25.124050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774374f1ee34'
down_revision = 'ba5640e9887e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
