"""added_columns_for_user

Revision ID: c374702dc1c2
Revises: 08826916cb07
Create Date: 2024-01-29 12:01:05.198842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c374702dc1c2'
down_revision = '08826916cb07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('license', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'license')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
