"""added_nullable_False_for_user_columns

Revision ID: ff3058e1e687
Revises: c374702dc1c2
Create Date: 2024-01-29 12:40:57.954027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff3058e1e687'
down_revision = 'c374702dc1c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'license',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'license',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
